services:
  app:
    build: .
    ports:
      - "3000:3000"  # Map port 3000 to the host
    volumes:
      - .:/app         # Mount the local project directory to the container
      - /app/node_modules # Use container's node_modules to avoid overwriting
    environment:
      NODE_ENV: development  # Set the environment to development
    command: npm run dev  # Start the development server
